### ISSUE TITLE
对比实验复现

### ISSUE THREAD

**Issue by kiwncia** [kwwcv/iaanet#1]
您好，很感谢您能开源代码，在您的论文中发现ALCnet进行了对比，ALCnet使用MXNet框架BUG多好多人没能复现出来，戴博士也没有具体说明，希望您能公开一下这个代码，非常感谢。

**Comment by kwwcv** [comment]
不是框架的BUG，是配环境的问题，MXNet框架配环境比较麻烦，在cuda10.2下配好环境能正常运行。
